version: '3.8'

services:
  # Apache + PHP Service
  www:
    image: php:8.2-apache
    volumes:
      - ./public:/var/www/html
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
      - MYSQL_DATABASE=lamp_db
    depends_on:
      - db

  # MySQL Service
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
    ports:
      - "3306:3306"

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - db

volumes:
  db_data:
