services:
  # Apache + PHP Service
  apache:
    build:
      context: ./
      dockerfile: ./Dockerfile.httpServer_apache
    container_name: apache
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./public:/var/www/html/
      - ./config/apache-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./certs:/etc/ssl/private
    depends_on:
      - db

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
    ports:
      - "3306:3306"

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - db

  evil:
    build:
      context: ./
      dockerfile: ./evil/Dockerfile.evil
    container_name: evil
    ports:
      - "9000:80"
    volumes:
      - ./evil:/app
    command: deno run --allow-read --allow-net -A main.ts

  blockchain_alice:
    build:
        context: ./
        dockerfile: ./Dockerfile.blockchain
    container_name: blockchain_alice
    expose:
        - "3000" # nodeaddress, only needed between nodes
    ports:
        - "7080:8080" # apiport, accessed from your command line
    volumes:
        - ./blockchain/blockchain_alice/:/app/simpleBlockchain/blockchain/
        - ./blockchain/existingWallets/wallet_alice:/app/simpleBlockchain/wallet_alice:ro
    command: ./cli server start -nodeaddress blockchain_alice:3000 -peernodeaddress blockchain_bob:3000 -walletname alice -ismining=true
  blockchain_bob:
    build:
        context: ./
        dockerfile: ./Dockerfile.blockchain
    container_name: blockchain_bob
    expose:
        - "3000" # nodeaddress, only needed between nodes
    ports:
        - "7081:8080" # apiport, accessed from your command line
    volumes:
    - ./blockchain/blockchain_bob/:/app/simpleBlockchain/blockchain/
    - ./blockchain/existingWallets/wallet_bob:/app/simpleBlockchain/wallet_bob:ro
    command: ./cli server start -nodeaddress blockchain_bob:3000 -peernodeaddress blockchain_alice:3000 -walletname bob

volumes:
  db_data:
