version: '3.8'

services:
  # Apache + PHP Service
  apache:
    build: .
    container_name: apache
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./public:/var/www/html/
      - ./config/apache-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./certs:/etc/ssl/private
    depends_on:
      - db

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
    ports:
      - "3306:3306"

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - db

  evil:
    build: ./evil
    container_name: evil
    ports:
      - "9000:80"
    volumes:
      - ./evil:/app
    command: deno run --allow-net -A main.ts


volumes:
  db_data:

