services:
  # Apache + PHP Service
  apache:
    build:
      context: ./
      dockerfile: ./Dockerfile.httpServer_apache
    container_name: apache
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./public:/var/www/html/
      - ./config/apache-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./certs:/etc/ssl/private
    depends_on:
      - db

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
    ports:
      - "3306:3306"

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - db

  evil:
    build:
      context: ./
      dockerfile: ./evil/Dockerfile.evil
    container_name: evil
    ports:
      - "9000:80"
    volumes:
      - ./evil:/app
    command: deno run --allow-read --allow-net -A main.ts

# The bank has a node on the server which is not allowed to mine
  blockchain_bank:
    build:
      context: ./
      dockerfile: ./blockchain/Dockerfile.blockchain
    container_name: blockchain_bank
    ports: # redirect ports to some starting with 70
      - "3000:3000" # nodeport 
      - "7080:8080" # apiport
    volumes:
      - ./blockchain/simpleBlockchain_bank.db:/app/simpleBlockchain/simpleBlockchain_3000.db
      - ./blockchain/existingWallets/wallet_bank:/app/simpleBlockchain/wallet_bank
    command: ./cli server start -nodeport 3000 -apiport 8080 -walletname bank -ismining=false

# Alice also lives on our server,
# This is rather unrealistic since that means that the servers docker composer is doing
# the mining as well, but it makes it very portable
  blockchain_alice:
    build:
      context: ./
      dockerfile: ./blockchain/Dockerfile.blockchain
    container_name: blockchain_alice
    ports: # redirect ports to some starting with 70
      - "7001:3000" # nodeport
      - "7081:8080" # apiport 
    volumes:
      - ./blockchain/simpleBlockchain_alice.db:/app/simpleBlockchain/simpleBlockchain_3000.db
      - ./blockchain/existingWallets/wallet_alice:/app/simpleBlockchain/wallet_alice
    command: ./cli server start -nodeport 3000 -apiport 8080 -walletname alice -ismining=true


volumes:
  db_data:

